# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: sample.fhir
canonical: http://test.com/fhir/sample
name: sampleIG
title: sampleIG Implementation Guide
status: draft
version: 0.1.2
description: A Sample IG
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

dependencies:
  #hl7.fhir.us.core: 3.1.1
  #hl7.fhir.uv.cpg: 0.1.0
  #hl7.fhir.uv.cpg: 
 
parameters:
#   show-inherited-invariants: false

# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds.
#groups:

pages:
  index.md:
    title: Home
 

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# The menu property will be used to generate the input/menu.xml file.
# The menu is represented as a simple structure where the YAML key
# is the menu item name and the value is the URL. The IG publisher
# currently only supports one level deep on sub-menus.
# To provide a custom menu.xml file, do not include this property and
# include a `menu.xml` file in input/includes.
menu:
  Home: index.html
  
  Artifacts: artifacts.html
